### ISSUE TITLE
README arduino instructions are out of date

### ISSUE THREAD

**Issue by logikal** [Xinyuan-LilyGO/T-Echo#15]
the Board to select instructions reference an item that doesn't exist.

https://github.com/Xinyuan-LilyGO/LilyGO-T-Echo/blob/main/README.MD?plain=1#L8

<img width="689" alt="image" src="https://user-images.githubusercontent.com/419745/166076903-9ed2488b-3fc1-4682-9b2e-389761c3863b.png">

**Comment by LilyGO** [comment]
Hello，You can select "Nordic nRF52840 DK"

**Comment by liangyingy** [comment]
Updated readme, see #14.  thanks!
