### ISSUE TITLE
Connect to xcsoar

### ISSUE THREAD

**Issue by BrianJSavage** [Xinyuan-LilyGO/T-Echo#35]
I am trying to connect to xcsoar running on my phone.
I connect bluetooth and the device appears in the devices list but I only get No Data appearing.

I have checked all the NMEA options in the Tool setup.

Help!!

Cheers

brian

**Comment by 777CHIP** [comment]
I am having the exact same issue on both of my T-Echo’s … Softrf

would really like a response

**Comment by lyusupov** [comment]
![xcs1](https://github.com/Xinyuan-LilyGO/T-Echo/assets/5849637/896ae63c-4240-47a5-a33f-d0ca36f93b08)

<br>
<br>
<br>

#

<br>
<br>
<br>

![xcs2](https://github.com/Xinyuan-LilyGO/T-Echo/assets/5849637/0c8f62dc-d179-49b5-89ce-6c483beee5b4)

<br>
<br>
<br>

#

<br>
<br>
<br>

![xcs3](https://github.com/Xinyuan-LilyGO/T-Echo/assets/5849637/7d33be10-6dd8-4aa1-82bb-e28102ec2614)

<br>
<br>
<br>

#

<br>
<br>
<br>

![xcs4](https://github.com/Xinyuan-LilyGO/T-Echo/assets/5849637/e7e399f3-a0c0-4d93-b634-2b09e521cbd9)

**Comment by BrianJSavage** [comment]
Thanks for the reply.

I did all that, the only change was setting protocol to OGNTP.

Still doesn't work, and still getting No Data on the port.

Also, on my XCSOAR the device shows up as BLE Sensor, not BLE Port as shown above. Not sure if this makes a difference.
I also used channel A as shown, as shown above which disables the built in GPS and sensors.

Cheers

Brian

**Comment by BrianJSavage** [comment]
I did unpair. reset everything and it didn't work when I replied before.
I just tried it again after your last comment, and it now works.
Thinking about it, the issue is that I thought I had to pair through Bluetooth, which I had to do to get SoftRF to work.
So it was still paired while I tried to attach to xcsoar.
Please confirm the solution is to not have it paired through Bluetooth, and it will connect.
This might be worth emphasising somewhere for other people, as to me it is counterintuitive.
Thanks for your help. Much appreciated.
Brian

**Comment by lyusupov** [comment]
<img width="279" alt="image" src="https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/5849637/236c0f78-faff-4d77-9ba4-8f1b1de94710">

**Comment by BrianJSavage** [comment]
Thanks for your help. All working
