### ISSUE TITLE
internal Flash Memory example??

### ISSUE THREAD

**Issue by richonguzman** [Xinyuan-LilyGO/T-Echo#42]
cant find any internal Flash Memory example to use this

**Comment by lyusupov** [comment]
https://github.com/adafruit/Adafruit_SPIFlash

**Comment by richonguzman** [comment]
> https://github.com/adafruit/Adafruit_SPIFlash

So I would need to read/write flash with flash examples or SDFlash examples?

PS: can flash memory be written with VSCODE>Platformio?

**Comment by lyusupov** [comment]
> So I would need to read/write flash with flash examples ...

Access to T-Echo's 2 Mbytes QSPI flash memory is possible with FAT filesystem and USB Mass Storage method. See this example:

https://github.com/lyusupov/SoftRF/wiki/Badge-Edition.-Aircrafts-database

**Comment by richonguzman** [comment]
so the flash data is added just the uf2 files when starting the USB Mass Storage method ??

on the same folder and all?

**Comment by lyusupov** [comment]
1) the uif2 firmware binary is applicable when the device in Adafruit **bootloader mode** only
2) in application mode (Arduino) -it is possible to use the same 'Drag and Drop' method as well, read 
   - Adafruit SPIflash examples and
   - Adafruit TinyUSB Arduino examples

**Comment by richonguzman** [comment]
> 1. the uif2 firmware binary is applicable when the device in Adafruit **bootloader mode** only
> 2. in **application mode** (Arduino) -it is possible to use the same 'Drag and Drop' method as well, read
>    
>    * **Adafruit SPIflash** examples and
>    * **Adafruit TinyUSB** Arduino examples
> 
> https://github.com/adafruit/Adafruit_TinyUSB_Arduino/tree/master/examples/MassStorage/msc_external_flash

sorry I got lost for a moment:

My The T-echo is running as "Adafruit bootloader mode" and I can upload like a "external mass flash disk" the .uf2 file and also through VSCODE+Platformio. This works fine.

But this is where I need to be specific: will I be able to add also a .json file into the flash of T-echo by copying it also to the "external mass flash disk" that "Adafruit bootloader mode" enables?

**Comment by lyusupov** [comment]
> will I be able to add also a .json file into the flash of T-echo by copying it also to the "external mass flash disk ...

Play with **msc_external_flash** sketch _(mentioned above)_ to answer your question by yourself.
You may borrow T-Echo specific GPIOs and flash types from SoftRF source code:
https://github.com/lyusupov/SoftRF/blob/master/software/firmware/source/SoftRF/src/platform/nRF52.cpp#L199-L233

**Comment by richonguzman** [comment]
> > will I be able to add also a .json file into the flash of T-echo by copying it also to the "external mass flash disk ...
> 
> Play with **msc_external_flash** sketch _(mentioned above)_ to answer your question by yourself. You may borrow T-Echo specific GPIOs and flash types from SoftRF source code: https://github.com/lyusupov/SoftRF/blob/master/software/firmware/source/SoftRF/src/platform/nRF52.cpp#L199-L233

thanks for the guidance!!!

 I will try (as this is all new to me) 

 ;)

**Comment by lyusupov** [comment]
<img width="279" alt="image" src="https://github.com/nakhonthai/ESP32APRS_T-TWR/assets/5849637/236c0f78-faff-4d77-9ba4-8f1b1de94710">
