### ISSUE TITLE
battery conversions help

### ISSUE THREAD

**Issue by richonguzman** [Xinyuan-LilyGO/T-Echo#52]
sample = analogRead(BATTERY_PIN);

voltage = sample * batteryConversion;

what are the conversions value to get real voltage / battery data?

**Comment by lyusupov** [comment]
https://github.com/Xinyuan-LilyGO/T-Echo/blob/main/T-Echo_Schematic.pdf

**Comment by richonguzman** [comment]
> https://github.com/Xinyuan-LilyGO/T-Echo/blob/main/T-Echo_Schematic.pdf

that was I missing!

thanks!
